### ISSUE TITLE
Support for R 3.6.2?

### ISSUE THREAD

**Issue by tmalsburg** [OscarKjell/text#1]
Cool package!  Unfortunately it requires R >= 4.0.0.  Like many others I'm using Ubuntu LTS (20.04) which contains R 3.6.2.  Any chance that this package could also be made to work with recent pre-4 version of R as well?

**Comment by OscarKjell** [comment]
Sorry for a late reply; but I have not been able so solve this. (and I am not sure I will be able to either.)
