### ISSUE TITLE
textTrainRandomForest seems to have a fatal bug

### ISSUE THREAD

**Issue by lilchow** [OscarKjell/text#104]
Dear developers,

I have attempted to use textTrainRandomForest to train multinomial classification models on at least two occassions (a six-category classification and a 12-category classification). I got pretty much the same error message each time. It seems that the model had been trained successfully but just was unable to be saved at the last step. I posted the error message for the six-category classification below. The message for the 12-category calssification is nearly identical except that the number in parenthesis after `truth` is 12 instead of 6. Could you take a look at the matter? Thank you very much!

Error in `yardstick::roc_auc()`:
! The number of levels in `truth` (6) must match the number of columns supplied in `...` (1).
Backtrace:
 1. text::textTrainRandomForest(...)
 2. text:::classification_results(...)
 4. yardstick:::roc_auc.data.frame(predy_y, truth, colnames(predy_y[3]))
 5. yardstick::prob_metric_summarizer(...)
 8. yardstick (local) fn(...)

**Comment by OscarKjell** [comment]
This is addressed in version 1.2.02. please have a try.
