### ISSUE TITLE
Question about tokens_deselect

### ISSUE THREAD

**Issue by LuigiC72** [OscarKjell/text#117]
I am using text (version 1.1.4)  and I have a question about tokens_deselect. According to the instructions, this option allows to deselect embeddings linked to specific tokens such as [CLS] and [SEP] for the context embeddings. I have tried but I don't see any difference compared to a situation wherein I don't use such option. For example:
system.time(x1 <- textEmbed("hello my name is John.", layers=11))

system.time(x2 <- textEmbed("hello my name is John.", layers=11, tokens_deselect="hello"))

or 

system.time(x4 <- textEmbed("hello my name is John.", layers=11, tokens_deselect=c("[CLS]", "hello")))

I have always get the same values for both the tokens and the texts. Am I missing something?
Thanks for any possible help!
Luigi

**Comment by OscarKjell** [comment]
Hi, 
Thanks for reporting this issue. This only worked using [textEmbedLayerAggregation()](https://r-text.org/reference/textEmbedLayerAggregation.html) before. But now using version 1.2.0.01 (downloaded from github), it will work. 
Note that the selection/deselection occurs in the textEmbedLayerAggregation() stage. 
So now these will yield different results. 

```
x1 <- text::textEmbed("hello, my name is John.", layers=11)
x2 <- text::textEmbed("hello, my name is John.", layers=11, tokens_deselect="hello")
x3 <- text::textEmbed("hello, my name is John.", layers=11, tokens_deselect=c("[CLS]"))
x4 <- textEmbed("hello, my name is John.", layers=11, tokens_select=c("[CLS]"))

```
