### ISSUE TITLE
textFineTuneTask error

### ISSUE THREAD

**Issue by LuigiC72** [OscarKjell/text#118]
I know that the function textFineTuneTask  is still under development. But I tried to implement it (I am using text version 1.1.4):

x <- system.time(textFineTuneTask(x_tot3, is_regression = FALSE)) 

- where x_tot3 is a dataframe where the first column contain text data, and the second column the to-be-predicted variable (numeric) and is_regression=FALSE given that I am dealing with a classification exercise, I get the following error: "Error: NameError: name 'AcceleratorState' is not defined". I am wondering if it is a problem of the still developing function, or I am doing some mistakes. 

Thanks for any possible help!
Luigi

**Comment by OscarKjell** [comment]
Please try this with the new version 1.2.

**Comment by OscarKjell** [comment]
if it does not work, please report again or if it is the same open this issue.

**Comment by LuigiC72** [comment]
Thanks for the reply. I have installed the new version of the package (1.2.0.2). Unfortunately I still get the same error: 
x <- system.time(textFineTuneTask(x_tot3, is_regression = FALSE))
Error: NameError: name 'AcceleratorState' is not defined
Thanks again for any possible help

**Comment by LuigiC72** [comment]
Thanks for the reply. I have installed the new version of the package (1.2.0.2). Unfortunately I still get the same error:
x <- system.time(textFineTuneTask(x_tot3, is_regression = FALSE))
Error: NameError: name 'AcceleratorState' is not defined
Thanks again for any possible help
