### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords) :    SystemError: <method 'lower' of 'str' objects> returned a result with an error set

### ISSUE THREAD

**Issue by tressoldi** [OscarKjell/text#12]
> library(text)
This is text (version 0.9.16). 
Text is new and still rapidly improving. 
Newer versions may have improved functions and updated defaults to reflect current understandings of the state-of-the-art. 
Please send us feedback based on your experience.
> library(reticulate)
> 
> text::textrpp_initialize(condaenv = "textrpp_condaenv2")
textrpp python option is already set, text will use:
	condaenv = "textrpp_condaenv2"
[nltk_data] Downloading package punkt to C:\Users\Admin.DESKTOP-6E4TRO
[nltk_data]     E\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

Successfully initialized text required python packages.

Python options: 
 type = "textrpp_condaenv", 
 name = "textrpp_condaenv2".
> # Import data 
> 
> Q<-read.csv("Q1NC.csv", header = TRUE, sep = ";")
> 
> sq_data <- Q
> 
> # Transform the text data to BERT word embeddings
> 
> wordembeddings <- textEmbed(sq_data, 
+                             model = 'bert-base-uncased')
[nltk_data] Downloading package punkt to C:\Users\Admin.DESKTOP-6E4TRO
[nltk_data]     E\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt to C:\Users\Admin.DESKTOP-6E4TRO
[nltk_data]     E\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  SystemError: <method 'lower' of 'str' objects> returned a result with an error set

Detailed traceback:
  File "<string>", line 53, in hgTransformerGetEmbedding

**Comment by OscarKjell** [comment]
Can you please let me know what kind of data you are trying to textEmbed? That is, it would be great to have a minimal reproducible example (please see here: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example).

**Comment by tressoldi** [comment]
Here attached
[Q1NC.csv](https://github.com/OscarKjell/text/files/7697391/Q1NC.csv)

**Comment by OscarKjell** [comment]
This works for me: 

```
Q1NC <- read.csv2("Q1NC.csv", sep=";")
Q1NC_embeddings <- textEmbed(Q1NC)
Q1NC_embeddings
```
Does it work for you?

**Comment by tressoldi** [comment]
Unfortunately not.
I got the same error message:
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  SystemError: <method 'lower' of 'str' objects> returned a result with an error set

Detailed traceback:
  File "<string>", line 53, in hgTransformerGetEmbedding

**Comment by OscarKjell** [comment]
It appears that your .csv file contains this string "\x92" for what I think should be a "'".

So please try change these strings and then run textEmbed:
```
Q1NC2$text_new <- str_replace_all(Q1NC2$text, "\x92", "'")
Q1NC_embeddings <- textEmbed(Q1NC2$text_new)
Q1NC_embeddings

```

**Comment by tressoldi** [comment]
Fixed, thank you very much.
A trivial problem, but I was not able to detect it in the file even using Notepad++

Best
Patrizio
