### ISSUE TITLE
textFineTuneTask error with new Text package

### ISSUE THREAD

**Issue by LuigiC72** [OscarKjell/text#144]
Thanks for the reply. I have installed the new version of the package (1.2.0.2). Unfortunately I still get the same error:
x <- system.time(textFineTuneTask(x_tot3, is_regression = FALSE))
Error: NameError: name 'AcceleratorState' is not defined
Thanks again for any possible help

_Originally posted by @LuigiC72 in https://github.com/OscarKjell/text/issues/118#issuecomment-1952537616_

**Comment by OscarKjell** [comment]
have you also re-installed the python environments? i.e., running below functions for the new update:

textrpp_install()
textrpp_initialize()

This is because we need to install new versions of Python libraries.

**Comment by LuigiC72** [comment]
I did that but unfortunately I still get the same error. More in details:

x_tot <- read.csv("disaster_tot.csv") # here the URL of the dataset: https://www.dropbox.com/scl/fi/0cz5qz2yuxf9d5mty4omq/disaster_tot.csv?rlkey=ls6e6ili22r3028svjwunkz4p&dl=0
x_tot$choose_one <- ifelse(x_tot $choose_one=="Disaster", 1, 0) # the class-labels
x_tot$text<- gsub("http.*","",x_tot$text)
x_tot2 <- x_tot[c(4,3)]
x_tot3 <- x_tot2[c(1:100),] # my training-set with 2 variables (texts and class-labels)
prove <- system.time(textFineTuneTask(x_tot3, is_regression = FALSE)) # the fitted model
Error: NameError: name 'AcceleratorState' is not defined

**Comment by OscarKjell** [comment]
thanks for the data and clear example. 

please note that this works for me: 

```
textFineTuneTask(x_tot3, 
                 is_regression = TRUE)

```
so please make sure again that you managed to install the 1.2 version of the text package, and that the following installation steps works. 
note that at the moment the classification task don't work. 

let me know how it goes.

**Comment by LuigiC72** [comment]
That's why it did not work! Yes, thanks. With is_regression=TRUE it works. Hopefully the classification option will be employed later on. Thanks once again for the help!
