### ISSUE TITLE
Error in textTrainRegression

### ISSUE THREAD

**Issue by HansBaum129** [OscarKjell/text#158]
I'm running the text tutorial for the Psych Methods article. I can get the embeddings etc., but when I try the following:

model_satisfactiontext_swls <- textTrain(
  x = word_embeddings$texts$satisfactiontexts, # the predictor variables (i.e., the word embeddings)
  y = Language_based_assessment_data_8$swlstotal, # the criterion variable (i.e.,the rating scale score.
  model_description = "author(s): Kjell, Giorgi, & Schwartz; data: N=40, population =  Online, Mechanical Turk; publication: title = Example for demo; description: swls = the satisfaction with life scale")

I get the following error message:

Fold: rmse 6.051 (duration: 17.34 secs). 
Fold: rmse 5.825 (duration: 32.09 secs). 
Fold: rmse 6.7 (duration: 20.46 secs). 
Fold: rmse 5.243 (duration: 20.81 secs). 
Fold: rmse 5.193 (duration: 21.18 secs). 
Fold: rmse 4.981 (duration: 21.14 secs). 
Fold: rmse 7.338 (duration: 21.14 secs). 
Fold: rmse 5.876 (duration: 20.33 secs). 
Fold: rmse 6.994 (duration: 21.36 secs). 
Fold: rmse 7.907 (duration: 21.14 secs). 
Error in `workflows::add_recipe()`:
! Can't add a trained recipe to a workflow.
Run `rlang::last_trace()` to see where the error occurred.
There were 21 warnings (use warnings() to see them)
> rlang::last_trace()
<error/rlang_error>
Error in `workflows::add_recipe()`:
! Can't add a trained recipe to a workflow.
---
Backtrace:
    ▆
 1. ├─text::textTrain(...)
 2. │ └─text::textTrainRegression(...)
 3. │   └─text (local) model_save_small_size(...)
 4. │     ├─base::with(...)
 5. │     └─base::with.default(...)
 6. │       └─base::eval(substitute(expr), data, enclos = parent.frame())
 7. │         └─base::eval(substitute(expr), data, enclos = parent.frame())
 8. │           └─... %>% workflows::add_recipe(final_recipe)
 9. └─workflows::add_recipe(., final_recipe)
Run rlang::last_trace(drop = FALSE) to see 2 hidden frames.

I'm using 2023.12.1 Build 402 with R version 4.3.3 (2024-02-29 ucrt).

Thanks.

**Comment by OscarKjell** [comment]
hi, thank you for the feedback. Can you please try using the latest version of text from Git Hub? 

# install.packages("devtools")
devtools::install_github("oscarkjell/text")


(might have to restart R to get the new changes to work). 

please let me know if this works.

**Comment by HansBaum129** [comment]
Dear Oscar,

Thanks for your rapid reply to my query. I'm away from the office today, but I will install the latest version of text tonight or tomorrow and get back to you as soon as I have more information.

Thanks again,

Hans
________________________________

**Comment by HansBaum129** [comment]
Dear Oscar,



I installed the newest version of text, as you suggested, and now the textTrain
function works as expected.

When I use the textEmbed function, I get the following message:



Not logged in!

Successfully logout to Huggingface!



I assume this is normal.



I went through the entire tutorial and I mostly received the output that I would
have expected based on your 2023 Psych Methods piece. However, I did receive a few
error messages (for the textPredict function, the centrality_plot$final_plot
output, and the textPCA function). The inputs that I used and the error messages
that I received are shown below for your information.



Thanks again for your help, and thanks for making the text package available.
I read your 2019 and 2023 Psych Methods pieces with great interest (although I
still have to digest some of the details), and I believe the text package will
be useful for my research.



Hans



---------------------------------------------------------------------





satisfaction_text_valence <- textPredict(valence_Warriner_L11,

  word_embeddings$texts$satisfactiontexts, dim_names = FALSE)



Error in `recipes::bake()`:

✖ The following required columns are missing from `new_data`: `id_nr`.

ℹ These columns have one of the following roles, which are required at `bake()` time:

  `id variable`.

ℹ If these roles are not required at `bake()` time, use `update_role_requirements(role

  = "your_role", bake = FALSE)`.

Run `rlang::last_trace()` to see where the error occurred.

> rlang::last_trace()

<error/rlang_error>

Error in `recipes::bake()`:

✖ The following required columns are missing from `new_data`: `id_nr`.

ℹ These columns have one of the following roles, which are required at `bake()` time:

  `id variable`.

ℹ If these roles are not required at `bake()` time, use `update_role_requirements(role

  = "your_role", bake = FALSE)`.

---

Backtrace:

     ▆

  1. ├─text::textPredict(...)

  2. │ └─... %>% dplyr::select(-id_nr)

  3. ├─dplyr::select(., -id_nr)

  4. ├─dplyr::arrange(., id_nr)

  5. ├─dplyr::full_join(., new_data_id_nr_col, by = "id_nr")

  6. ├─dplyr::select(., -!!target_variables_names)

  7. ├─dplyr::bind_cols(...)

  8. │ └─rlang::list2(...)

  9. ├─stats::predict(...)

 10. └─workflows:::predict.workflow(...)

 11.   └─workflows:::forge_predictors(new_data, workflow)

 12.     ├─hardhat::forge(new_data, blueprint = mold$blueprint)

 13.     └─hardhat:::forge.data.frame(new_data, blueprint = mold$blueprint)

 14.       ├─hardhat::run_forge(blueprint, new_data = new_data, outcomes = outcomes)

 15.       └─hardhat:::run_forge.default_recipe_blueprint(...)

 16.         └─hardhat:::forge_recipe_default_process(...)

 17.           ├─recipes::bake(object = rec, new_data = new_data)

 18.           └─recipes:::bake.recipe(object = rec, new_data = new_data)



run rlang::last_trace(drop = FALSE) to see 4 hidden frames.



--------------------------------------------------------------



centrality_plot <- textCentralityPlot(word_data = centrality_results,

                                      min_freq_words_test = 2,

                                      plot_n_word_extreme = 10,

                                      plot_n_word_frequency = 5,

                                      plot_n_words_middle = 5,

                                      title_top = "Satisfaction with life word norm:

Semantic Centrality Plot",

                                      x_axes_label = "Satisfaction with Life Semantic

Centrality")



centrality_plot$final_plot



Error in `ggplot2::geom_point()`:

! Problem while computing aesthetics.

ℹ Error occurred in the 1st layer.

Caused by error:

! object 'only_x_dimension' not found

Run `rlang::last_trace()` to see where the error occurred.

> rlang::last_trace()

<error/rlang_error>

Error in `ggplot2::geom_point()`:

! Problem while computing aesthetics.

ℹ Error occurred in the 1st layer.

Caused by error:

! object 'only_x_dimension' not found

---

Backtrace:

     ▆

  1. ├─base (local) `<fn>`(x)

  2. └─ggplot2:::print.ggplot(x)

  3.   ├─ggplot2::ggplot_build(x)

  4.   └─ggplot2:::ggplot_build.ggplot(x)

  5.     └─ggplot2:::by_layer(...)

  6.       ├─rlang::try_fetch(...)

  7.       │ ├─base::tryCatch(...)

  8.       │ │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)

  9.       │ │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])

 10.       │ │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)

 11.       │ └─base::withCallingHandlers(...)

 12.       └─ggplot2 (local) f(l = layers[[i]], d = data[[i]])

 13.         └─l$compute_aesthetics(d, plot)

 14.           └─ggplot2 (local) compute_aesthetics(..., self = self)

 15.             └─base::lapply(aesthetics, eval_tidy, data = data, env = env)

 16.               └─rlang (local) FUN(X[[i]], ...)

Run rlang::last_trace(drop = FALSE) to see 5 hidden frames.



-------------------------------------------------------------------------------------

textPCA_results <- textPCA(words = Language_based_assessment_data_8$satisfactionwords,

                        word_types_embeddings = harmony_words_embeddings$word_types)



Error in `dplyr::select()`:

! `select()` doesn't handle lists.

Run `rlang::last_trace()` to see where the error occurred.

> rlang::last_trace()

<error/rlang_error>

Error in `dplyr::select()`:

! `select()` doesn't handle lists.

---

Backtrace:

    ▆

 1. ├─text::textPCA(...)

 2. │ └─base::sapply(...)

 3. │   └─base::lapply(X = X, FUN = FUN, ...)

 4. │     └─text (local) FUN(X[[i]], ...)

 5. │       └─single_word_embeddings1 %>% ...

 6. ├─dplyr::select(., dplyr::starts_with("Dim"))

 7. └─dplyr:::select.list(., dplyr::starts_with("Dim"))

Run rlang::last_trace(drop = FALSE) to see 1 hidden frame.




________________________________

**Comment by OscarKjell** [comment]
thanks for the feedback.
(I will update these for the tutorial)
