### ISSUE TITLE
R version

### ISSUE THREAD

**Issue by asheetal** [OscarKjell/text#16]
I see that this needs R version 4.0. Any specific feature of 4.0 used? I am trying to get it run on 3.6.3

**Comment by OscarKjell** [comment]
hmm I can't remember exactly what was not functioning with lower versions of R; but I think it might have been something to do with textEmbed, and sourcing the python function. Perhaps try running this line, and report the potential error you get in R 3.6.3, and it might jogg my memory. 
 
`reticulate::source_python(system.file("python", "huggingface_Interface3.py", package = "text", mustWork = TRUE))`

It is also possible that newer versions of reticulate have fixed a previous error...
