### ISSUE TITLE
Problem using valence trained prediction model

### ISSUE THREAD

**Issue by promothesh** [OscarKjell/text#187]
# Apply the model to the satisfaction text
> satisfaction_text_valence <- textPredict(valence_Warriner_L11,
+                                          word_embeddings$texts$satisfactiontexts,
+                                          dim_names = FALSE)
Error in UseMethod("bake") : 
  no applicable method for 'bake' applied to an object of class "NULL"

**Comment by OscarKjell** [comment]
Thank you for reporting this. 
I had to re-train the model with a newer version of text. Please down load the tutorial file again from osf. https://osf.io/dgczt/ 
and try again.

**Comment by OscarKjell** [comment]
feel free to open this up if something else comes up.
