### ISSUE TITLE
Problem with textTopicsTree()

### ISSUE THREAD

**Issue by LuigiC72** [OscarKjell/text#189]
I am using the latest version of text. I have an issue dealing with the function textTopicsTree. After running a BERTopic and correctly getting the results, if I type:

textTopicsTree(bertTopc, nyt2, "text")

I get the following error:
Error in get_topic_tree(topic_model, data, data_var) : 
  could not find function "get_topic_tree"

Thanks for any possible help,
Best,
Luigi

**Comment by OscarKjell** [comment]
Please note that this function is still under development, so I am closing this issue – thanks for reporting it though... it is always good to know that people are interested in the function. Hopefully we get time to complete the function in the nea future. 
If you are interested in doing LDA-topics you can also try out out other R-package https://r-topics.org/
