### ISSUE TITLE
Fatal Error when Running textrpp_initialize()

### ISSUE THREAD

**Issue by scm1210** [OscarKjell/text#192]
Hi, 

When running `textrpp_initialize()` I encounter a fatal error: OMP: Error #15: Initializing libomp.dylib, but found libomp.dylib already initialized.
when running in R Studio v 4.4.1.  I've replicated the error with both the cran and github verisons of text. 

I've tried to troubleshoot the issue to no avail.

My machine specs are 
M series chip 
mac os 14.6

Thanks in advance,
Steven

**Comment by OscarKjell** [comment]
thanks a lot for updating us on this; @moomoofarm1 do you see some solution for this? 

(I think the problem concerns the different python packages required for the two versions)

**Comment by moomoofarm1** [comment]
> `seems to be an issue with the latest version of the package.

i was able to install version 1.2.1 and circumnavigate the issue`

Might be due to some compatibility issues with R version. Try downgrade R to version 4.3.1. It might help.

**Comment by moomoofarm1** [comment]
An additional solution might be this.

This code will remove miniconda.
`unlink(reticulate::miniconda_path(), recursive = TRUE, force = TRUE)

file.exists(reticulate::miniconda_path())`

This code will remove all the installed R packages.
`ip <- as.data.frame(installed.packages()[,c(1,3:4)])
rownames(ip) <- NULL
ip <- ip[is.na(ip$Priority),1:2,drop=FALSE]
print(ip, row.names=FALSE)

# Remove all user installed packages, without removing any base packages for R or MRO.
# create a list of all installed packages
ip <- as.data.frame(installed.packages())
head(ip)
# if you use MRO, make sure that no packages in this library will be removed
ip <- subset(ip, !grepl("MRO", ip$LibPath))
# we don't want to remove base or recommended packages either\
ip <- ip[!(ip[,"Priority"] %in% c("base", "recommended")),]
# determine the library where the packages are installed
path.lib <- unique(ip$LibPath)
# create a vector with all the names of the packages you want to remove
pkgs.to.remove <- ip[,1]
head(pkgs.to.remove)
# remove the packages
sapply(pkgs.to.remove, remove.packages, lib = path.lib)`

Try to install using the code below.
`install.packages('text')
text::textrpp_install()

reticulate::py_run_string(
  'import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

import torch
import huggingface_hub
from transformers import AutoConfig, AutoModel, AutoTokenizer
try:
    from transformers.utils import logging
except ImportError:
    print("Warning: Unable to importing transformers.utils logging")
from transformers import pipeline
import numpy as np

import nltk
try:
    nltk.data.find("tokenizers/punkt/PY3/english.pickle")
except:
    nltk.download("punkt")

from nltk.tokenize import sent_tokenize

import os, sys'
)

text::textrpp_initialize(save_profile = TRUE)`

**Comment by moomoofarm1** [comment]
Maybe you could try the alternative (not sure) to change the torch from 2.2.0 (default for text package v1.2.3) to 2.1.0 to solve the issue. We will possibly update this later.

**Comment by OscarKjell** [comment]
We have now also included information about this on the www.r-text.org website: https://r-text.org/articles/huggingface_in_r_extended_installation_guide.html#solving-omp-errors-and-rrstudio-crashes
