### ISSUE TITLE
Impossible to make the text package run after textrpp_initialize()

### ISSUE THREAD

**Issue by myliserta** [OscarKjell/text#196]
I am using an Apple Silicon processor, M2. With RStudio Version 2024.04.2+764 (2024.04.2+764) and R 4.4.0

After running textrpp_install()
textrpp_install()
info: downloading installer
error: could not amend shell profile: '/Users/abcd/.profile': could not write rcfile file: '/Users/abcd/.profile': Permission denied (os error 13)
Confirm that a new conda environment will be set up. 
1: Confirm
2: Cancel

O confirm and get Installation is completed.

 Condaenv: textrpp_condaenv 

After I run the textrpp_initialize() function, I get "R Session Aborted" R encountered a fatal error. The session was terminated. No matter what I do. Please advise me. Does it have anything to do with the environment? Where do I need to act? IS the Tools > Global Options > Python part involved?

**Comment by OscarKjell** [comment]
Hi, do you have permission to install new programs on your computer?

**Comment by myliserta** [comment]
Yes, I have full control over my computer. I have tried with several versions, the only one that works is text 1.2.1. Whenever I try to install 1.2.3 directly from CRAN or 1.2.7 from github, it just goes into a fatal error.

**Comment by OscarKjell** [comment]
This is stange. Have you been able to solve it? 

If you look at the github actions, you can see how the package is being installed and run on Mac. Maybe that can be some help. https://github.com/OscarKjell/text/actions/runs/11378882665/job/31655413452

**Comment by myliserta** [comment]
Thank you for this, I will try it out. I will also contact you via email; I hope my message will not end up in the spam folder.

**Comment by OscarKjell** [comment]
Did you solve this issue, and in that case how?

**Comment by OscarKjell** [comment]
Please see the information about this here: https://r-text.org/articles/huggingface_in_r_extended_installation_guide.html#solving-omp-errors-and-rrstudio-crashes 

If this does not solve the issue, please feel free to open a new issue. 

Thank you for the feedback.
