### ISSUE TITLE
Issues with rpytools

### ISSUE THREAD

**Issue by hudsonpf** [OscarKjell/text#197]
I am running this on Windows 10 with RStudio version 2024.09.0 Build 375, R version 4.1.2, text version 1.39.0. 

I was able to get the text package installed and run textrpp_install() but I cannot use any functions in the package. When  I attempt to run textrpp_initialize(save_profile = TRUE), I get the following error: 

 **textrpp_initialize(save_profile = TRUE)
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'rpytools'
Run `reticulate::py_last_error()` for details.**

I see that I have the rpytools package located in my R bin under the reticulate package. I have also tried downloading the text package both through CRAN and via Github. I have tried many different solutions but with no luck. Is there something wrong with how my environment is being set up?

**Comment by OscarKjell** [comment]
I have not seen this error before. I have you been able to solve it?  Normally we are not directly install this pacakge. However, perhaps running this: 
textrpp_install(
  conda = "auto",
  update_conda = TRUE,
  force_conda = TRUE,
  rpp_version = c(
    "torch==2.2.0",
    "transformers==4.38.0",
    "huggingface_hub==0.20.0",
    "numpy==1.26.0",
    "pandas==2.0.3",
    "nltk==3.8.1",
    "scikit-learn==1.3.0",
    "datasets==2.16.1",
    "evaluate==0.4.0",
    "accelerate==0.26.0",
    "bertopic==0.16.3",
    "jsonschema==4.19.2",
    "sentence-transformers==2.2.2",
    "flair==0.13.0",
    "umap-learn==0.5.6",
    "hdbscan==0.8.33",
    "scipy==1.10.1", 
    "rpytools"
  ),
  envname = "textrpp_condaenv",
  pip = TRUE,
  python_path = NULL,
  prompt = TRUE
)
