### ISSUE TITLE
Support for other tasks: Zero-Shot Classification?

### ISSUE THREAD

**Issue by carlosbgueiros** [OscarKjell/text#23]
Great and useful package! 
A quick question/feature request: Do you plan to include other tasks like Zero-Shot Classification? Or possibly  a way to use 
textClassify() with Zero-Shot Classification models? 
Thanks

**Comment by sjgiorgi** [comment]
Right now we offer a few other tasks (text generation, named entity recognition, etc.) but not zero-shot classification. See the documentation [here](https://r-text.org/reference/index.html#language-analysis-tasks). We've just added these, so they aren't available through CRAN yet, but will be shortly (hopefully). I can add zero-shot classification in the next week. 

Thank you for the kind feedback!

**Comment by OscarKjell** [comment]
Sorry for the delay of implementing the R-code for the zero-shot function -- we're working on get a 1.0 version ready for CRAN. But for now you can use the textZeroShot() function in the development version of text from github (version 0.9.99). Please let us know if you have any feedback.

**Comment by carlosbgueiros** [comment]
So far, the zero-shot function works well in the development version  (version 0.9.99). I had to manually install PyTorch with Cuda support via the terminal to get GPU support, as only "device=cpu" worked out of the box. Besides that, everything works fine. Thank you for the implementation.
