### ISSUE TITLE
Error with textEmbed

### ISSUE THREAD

**Issue by nicosims** [OscarKjell/text#31]
I got this error while running textEmbed:

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
> ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.

Looking it up I see how people fixed this issue directly in python, but I'm not sure how it would work here.

**Comment by nicosims** [comment]
it looks like this is just a problem for gpt2

**Comment by OscarKjell** [comment]
yes, please note that gpt2 can be used for, e.g., generating text and summaries text and other tasks, but not for receiving word embeddings using textEmbed.

**Comment by OscarKjell** [comment]
which version of the text-pacakge are you using? 
This works for me: 
```
textEmbed("hello", 
          model = "gpt2")
```

**Comment by smburns47** [comment]
I also get this error when trying to use the gpt2 model in particular (need a model that allows for more that 512 tokens). @OscarKjell do you have a recommendation for this?

**Comment by OscarKjell** [comment]
GPT2 you can use for text generation in textGeneration; but not for getting embeddings in textEmbed.
