### ISSUE TITLE
textrpp_initialize() throws error on Linux x86 (module system)

### ISSUE THREAD

**Issue by jjbrehm** [OscarKjell/text#32]
I am trying to install the `text` library, and while the install command works without error, the next step, textrpp_initialize(), throws a segfault.

I am running the job on our university machines, which use a module architecture. I have run the installation both w/ and w/o the python/anaconda-2021.05 module.

Is this an error on my fault, or in the library?

 *** caught segfault ***
address 0x90, cause 'memory not mapped'

Traceback:
 1: py_initialize(config$python, config$libpython, config$pythonhome,     config$virtualenv_activate, config$version >= "3.0", interactive(),     numpy_load_error)
 2: (function() {    Sys.setenv(PYTHONPATH = newpythonpath)    on.exit(Sys.setenv(PYTHONPATH = oldpythonpath), add = TRUE)    py_initialize(config$python, config$libpython, config$pythonhome,         config$virtualenv_activate, config$version >= "3.0",         interactive(), numpy_load_error)})()
 3: doTryCatch(return(expr), name, parentenv, handler)
 4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5: tryCatchList(expr, classes, parentenv, handlers)
 6: tryCatch({    oldpythonpath <- Sys.getenv("PYTHONPATH")    newpythonpath <- Sys.getenv("RETICULATE_PYTHONPATH", unset = paste(config$pythonpath,         system.file("python", package = "reticulate"), sep = .Platform$path.sep))    local({        Sys.setenv(PYTHONPATH = newpythonpath)        on.exit(Sys.setenv(PYTHONPATH = oldpythonpath), add = TRUE)        py_initialize(config$python, config$libpython, config$pythonhome,             config$virtualenv_activate, config$version >= "3.0",             interactive(), numpy_load_error)    })}, error = function(e) {    Sys.setenv(PATH = oldpath)    if (is.na(curr_session_env)) {        Sys.unsetenv("R_SESSION_INITIALIZED")    }    else {        Sys.setenv(R_SESSION_INITIALIZED = curr_session_env)    }    stop(e)})
 7: initialize_python(required_module, use_environment)
 8: ensure_python_initialized()
 9: py_run_file(file, local = FALSE, convert = convert)
10: reticulate::source_python(system.file("python", "huggingface_Interface3.py",     package = "text", mustWork = TRUE))
11: textrpp_initialize()

**Comment by OscarKjell** [comment]
I have not run into this error before. Did you manage to fix it? 
Perhaps it you find it useful to see how the package i being installed in the Github actions on a Linux system (https://github.com/OscarKjell/text/actions/runs/3741890506)

Also, here they appear to have a segafault issues that gets resolved by reinstalling packages https://stackoverflow.com/questions/25672974/caught-segfault-error-in-r.

sorry for not being able to be more helpful.

**Comment by OscarKjell** [comment]
.
