### ISSUE TITLE
textEmbed default layers argument does not work with model = 'distilroberta-base'

### ISSUE THREAD

**Issue by sebsilas** [OscarKjell/text#35]
The following does not work for the `distilroberta-base` model class.

```
test <- text::textEmbed("hi there", model = 'distilroberta-base')

```
But if you explicitly call the second-to-last layer, rather than using the -2 default, (here, layer 5), it works:

```
test2 <- text::textEmbed("hi there", model = 'distilroberta-base', layers = 5)
```

**Comment by OscarKjell** [comment]
Thank you for reporting this. Please note that this should work with new versions of the text package now (currently need to download it from github; version .9.99.7 and above).
