### ISSUE TITLE
Error in py_run_file_impl(file, local, convert) :    ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by tressoldi** [OscarKjell/text#4]
after the following commands:
>library(text)
>wordembeddings <- textEmbed(Language_based_assessment_data_8)

I got:
>Error in py_run_file_impl(file, local, convert) : 
  ModuleNotFoundError: No module named 'torch'

The library torch is already installed in R

**Comment by OscarKjell** [comment]
Hi, have you tried follow the advice here: [http://r-text.org/articles/Extended_Installation_Guide.html](http://r-text.org/articles/Extended_Installation_Guide.html) ?

**Comment by tressoldi** [comment]
all run well until the command
> conda_install(envname = 'r-reticulate', c('torch==0.4.1', 'transformers==3.3.1', 'numpy', 'nltk'))
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - torch==0.4.1

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


Error: one or more Python packages failed to install [error code 1]

**Comment by OscarKjell** [comment]
hmmm have you also tried: 
´´´conda_install(envname = 'r-reticulate', c('torch==0.4.1', 'transformers==3.3.1', 'numpy', 'nltk'), pip = TRUE)´´´

**Comment by tressoldi** [comment]
Here the output:
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: C:\Users\Admin.DESKTOP-6E4TROE\AppData\Local\r-miniconda\envs\r-reticulate\Include\UNKNOWN
sysconfig: C:\Users\Admin.DESKTOP-6E4TROE\AppData\Local\r-miniconda\envs\r-reticulate\Include
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
ERROR: Could not find a version that satisfies the requirement torch==0.4.1 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.0, 1.7.1, 1.8.0, 1.8.1)
ERROR: No matching distribution found for torch==0.4.1
Error: Error installing package(s): "torch==0.4.1", "transformers==3.3.1", "numpy", "nltk"

**Comment by charlesk1** [comment]
I am experiencing the same problem.  I have also tried the Extended Installation Guide

**Comment by OscarKjell** [comment]
Hi @tressoldi and @charlesk1, 
Have you tried this: https://github.com/OscarKjell/text/issues/5#issuecomment-835306598 ?
Kind Regards, 
Oscar

**Comment by tressoldi** [comment]
Tried just now, but without success.
Sorry.
Patrizio

**Comment by OscarKjell** [comment]
@tressoldi and @charlesk1 
We have now developed improved routines for the installation process. It is important to get a python version that works with the right versions of python packages for the right OS. The new installations routines give you more control; but it should also just be to use the current defaults. (we have also set up github actions that test the installation for different OS and versions)
 
So can you please try download the github version of text (i.e., at least version 0.9.16) and follow the installation guidelines at https://r-text.org/articles/Extended_Installation_Guide.html

**Comment by tressoldi** [comment]
After installing the 0.9.16 version, and running the following command:
>text::textrpp_install()
I got:
Selection: 2
A new conda environment "textrpp_condaenv" will be created and 
python required packages: torch==1.7.1, transformers==4.12.5, numpy, nltk will be installed.  Creating textrpp_condaenv conda environment for text installation...
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Admin.DESKTOP-6E4TROE\AppData\Local\r-miniconda\envs\textrpp_condaenv

  added / updated specs:
    - python=3.9.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2021.10.8  |       h5b45459_0         176 KB  conda-forge
    openssl-1.1.1l             |       h8ffe710_0         5.7 MB  conda-forge
    pip-21.3.1                 |     pyhd8ed1ab_0         1.2 MB  conda-forge
    python-3.9.0               |h7840368_5_cpython        21.2 MB  conda-forge
    python_abi-3.9             |           2_cp39           4 KB  conda-forge
    setuptools-59.4.0          |   py39hcbf5309_0         1.0 MB  conda-forge
    sqlite-3.37.0              |       h8ffe710_0         1.2 MB  conda-forge
    tzdata-2021e               |       he74cb21_0         121 KB  conda-forge
    ucrt-10.0.20348.0          |       h57928b3_0         1.2 MB  conda-forge
    vc-14.2                    |       hb210afc_5          13 KB  conda-forge
    vs2015_runtime-14.29.30037 |       h902a5da_5         1.3 MB  conda-forge
    wheel-0.37.0               |     pyhd8ed1ab_1          31 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        33.1 MB

The following NEW packages will be INSTALLED:

  ca-certificates    conda-forge/win-64::ca-certificates-2021.10.8-h5b45459_0
  openssl            conda-forge/win-64::openssl-1.1.1l-h8ffe710_0
  pip                conda-forge/noarch::pip-21.3.1-pyhd8ed1ab_0
  python             conda-forge/win-64::python-3.9.0-h7840368_5_cpython
  python_abi         conda-forge/win-64::python_abi-3.9-2_cp39
  setuptools         conda-forge/win-64::setuptools-59.4.0-py39hcbf5309_0
  sqlite             conda-forge/win-64::sqlite-3.37.0-h8ffe710_0
  tzdata             conda-forge/noarch::tzdata-2021e-he74cb21_0
  ucrt               conda-forge/win-64::ucrt-10.0.20348.0-h57928b3_0
  vc                 conda-forge/win-64::vc-14.2-hb210afc_5
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.29.30037-h902a5da_5
  wheel              conda-forge/noarch::wheel-0.37.0-pyhd8ed1ab_1



Downloading and Extracting Packages
sqlite-3.37.0        | 1.2 MB    | ########## | 100% 
ca-certificates-2021 | 176 KB    | ########## | 100% 
wheel-0.37.0         | 31 KB     | ########## | 100% 
ucrt-10.0.20348.0    | 1.2 MB    | ########## | 100% 
pip-21.3.1           | 1.2 MB    | ########## | 100% 
vc-14.2              | 13 KB     | ########## | 100% 
python_abi-3.9       | 4 KB      | ########## | 100% 
python-3.9.0         | 21.2 MB   | ########## | 100% 
vs2015_runtime-14.29 | 1.3 MB    | ########## | 100% 
setuptools-59.4.0    | 1.0 MB    | ########## | 100% 
tzdata-2021e         | 121 KB    | ########## | 100% 
openssl-1.1.1l       | 5.7 MB    | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 4.10.3

Please update conda by running

    $ conda update -n base -c defaults conda


#
# To activate this environment, use
#
#     $ conda activate textrpp_condaenv
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Installing text required python packages...
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/torch/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/torch/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/torch/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/torch/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/torch/
Could not fetch URL https://pypi.org/simple/torch/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/torch/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement torch==1.7.1 (from versions: none)
ERROR: No matching distribution found for torch==1.7.1
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
Error: Error installing package(s): "torch==1.7.1", "transformers==4.12.5", "numpy", "nltk"

> reticulate::conda_list()
              name
1      r-miniconda
2     r-reticulate
3 textrpp_condaenv
                                                                                             python
1                         C:\\Users\\Admin.DESKTOP-6E4TROE\\AppData\\Local\\r-miniconda\\python.exe
2     C:\\Users\\Admin.DESKTOP-6E4TROE\\AppData\\Local\\r-miniconda\\envs\\r-reticulate\\python.exe
3 C:\\Users\\Admin.DESKTOP-6E4TROE\\AppData\\Local\\r-miniconda\\envs\\textrpp_condaenv\\python.exe
> text::textrpp_initialize(save_profile = TRUE)
Error in py_run_file_impl(file, local, convert) : 
  ModuleNotFoundError: No module named 'torch'

**Comment by OscarKjell** [comment]
Thanks for checking so quickly; and for providing the output.

Could you please try it again after having updated or reinstalled miniconda? 

# update mini_conda
reticulate::install_miniconda(update = TRUE, force = FALSE)

#Or if necessary reinstall. 
##reticulate::install_miniconda(update = TRUE, force = TRUE)

# And then again install text, but with a new environment name
 text::textrpp_install(envname = "textrpp_condaenv2")

# And initialize above env
text::textrpp_initialize(condaenv = "textrpp_condaenv2")

Please let me know if it works; and if it doesn't work please provide the output as above and whether you are running the latest version of Windows. 

Thanks!
Oscar

**Comment by tressoldi** [comment]
New attempt
> reticulate::install_miniconda(update = TRUE, force = TRUE)
* Downloading "https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe" ...
trying URL 'https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe'
Content type 'application/octet-stream' length 60924672 bytes (58.1 MB)
downloaded 58.1 MB

* Installing Miniconda -- please wait a moment ...
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Admin.DESKTOP-6E4TROE\AppData\Local\r-miniconda

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2021.10.26 |       haa95532_2         115 KB
    certifi-2021.10.8          |   py39haa95532_0         152 KB
    cffi-1.15.0                |   py39h2bbff1b_0         224 KB
    charset-normalizer-2.0.4   |     pyhd3eb1b0_0          35 KB
    cryptography-35.0.0        |   py39h71e12ea_0         991 KB
    idna-3.3                   |     pyhd3eb1b0_0          49 KB
    openssl-1.1.1l             |       h2bbff1b_0         4.8 MB
    pip-21.2.4                 |   py39haa95532_0         1.8 MB
    pycparser-2.21             |     pyhd3eb1b0_0          94 KB
    pyopenssl-21.0.0           |     pyhd3eb1b0_1          49 KB
    pywin32-228                |   py39hbaba5e8_1         5.6 MB
    requests-2.26.0            |     pyhd3eb1b0_0          59 KB
    setuptools-58.0.4          |   py39haa95532_0         778 KB
    tqdm-4.62.3                |     pyhd3eb1b0_1          83 KB
    tzdata-2021e               |       hda174b7_0         112 KB
    urllib3-1.26.7             |     pyhd3eb1b0_0         111 KB
    wheel-0.37.0               |     pyhd3eb1b0_1          33 KB
    wincertstore-0.2           |   py39haa95532_2          15 KB
    ------------------------------------------------------------
                                           Total:        15.1 MB

The following NEW packages will be INSTALLED:

  charset-normalizer pkgs/main/noarch::charset-normalizer-2.0.4-pyhd3eb1b0_0

The following packages will be REMOVED:

  chardet-4.0.0-py39haa95532_1003

The following packages will be UPDATED:

  ca-certificates                       2021.7.5-haa95532_1 --> 2021.10.26-haa95532_2
  certifi                          2021.5.30-py39haa95532_0 --> 2021.10.8-py39haa95532_0
  cffi                                1.14.6-py39h2bbff1b_0 --> 1.15.0-py39h2bbff1b_0
  cryptography                         3.4.7-py39h71e12ea_0 --> 35.0.0-py39h71e12ea_0
  idna                                    2.10-pyhd3eb1b0_0 --> 3.3-pyhd3eb1b0_0
  openssl                                 1.1.1k-h2bbff1b_0 --> 1.1.1l-h2bbff1b_0
  pip                                 21.1.3-py39haa95532_0 --> 21.2.4-py39haa95532_0
  pycparser                                       2.20-py_2 --> 2.21-pyhd3eb1b0_0
  pyopenssl                             20.0.1-pyhd3eb1b0_1 --> 21.0.0-pyhd3eb1b0_1
  pywin32                                228-py39he774522_0 --> 228-py39hbaba5e8_1
  requests                              2.25.1-pyhd3eb1b0_0 --> 2.26.0-pyhd3eb1b0_0
  setuptools                          52.0.0-py39haa95532_0 --> 58.0.4-py39haa95532_0
  tqdm                                  4.61.2-pyhd3eb1b0_1 --> 4.62.3-pyhd3eb1b0_1
  tzdata                                   2021a-h52ac0ba_0 --> 2021e-hda174b7_0
  urllib3                               1.26.6-pyhd3eb1b0_1 --> 1.26.7-pyhd3eb1b0_0
  wheel                                 0.36.2-pyhd3eb1b0_0 --> 0.37.0-pyhd3eb1b0_1
  wincertstore                           0.2-py39h2bbff1b_0 --> 0.2-py39haa95532_2



Downloading and Extracting Packages
charset-normalizer-2 | 35 KB     | ########## | 100% 
cffi-1.15.0          | 224 KB    | ########## | 100% 
pycparser-2.21       | 94 KB     | ########## | 100% 
pip-21.2.4           | 1.8 MB    | ########## | 100% 
pywin32-228          | 5.6 MB    | ########## | 100% 
ca-certificates-2021 | 115 KB    | ########## | 100% 
urllib3-1.26.7       | 111 KB    | ########## | 100% 
pyopenssl-21.0.0     | 49 KB     | ########## | 100% 
setuptools-58.0.4    | 778 KB    | ########## | 100% 
openssl-1.1.1l       | 4.8 MB    | ########## | 100% 
wincertstore-0.2     | 15 KB     | ########## | 100% 
idna-3.3             | 49 KB     | ########## | 100% 
cryptography-35.0.0  | 991 KB    | ########## | 100% 
requests-2.26.0      | 59 KB     | ########## | 100% 
tqdm-4.62.3          | 83 KB     | ########## | 100% 
wheel-0.37.0         | 33 KB     | ########## | 100% 
tzdata-2021e         | 112 KB    | ########## | 100% 
certifi-2021.10.8    | 152 KB    | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Admin.DESKTOP-6E4TROE\AppData\Local\r-miniconda\envs\r-reticulate

  added / updated specs:
    - numpy
    - python=3.6


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    intel-openmp-2021.4.0      |    h57928b3_3556         3.2 MB  conda-forge
    libblas-3.9.0              |     12_win64_mkl         4.5 MB  conda-forge
    libcblas-3.9.0             |     12_win64_mkl         4.5 MB  conda-forge
    liblapack-3.9.0            |     12_win64_mkl         4.5 MB  conda-forge
    mkl-2021.4.0               |     h0e2418a_729       181.7 MB  conda-forge
    python-3.6.15              |h39d44d4_0_cpython        18.9 MB  conda-forge
    python_abi-3.6             |          2_cp36m           4 KB  conda-forge
    tbb-2021.4.0               |       h2d74725_1         149 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       217.4 MB

The following NEW packages will be INSTALLED:

  certifi            pkgs/main/noarch::certifi-2020.6.20-pyhd3eb1b0_3
  intel-openmp       conda-forge/win-64::intel-openmp-2021.4.0-h57928b3_3556
  libblas            conda-forge/win-64::libblas-3.9.0-12_win64_mkl
  libcblas           conda-forge/win-64::libcblas-3.9.0-12_win64_mkl
  liblapack          conda-forge/win-64::liblapack-3.9.0-12_win64_mkl
  mkl                conda-forge/win-64::mkl-2021.4.0-h0e2418a_729
  numpy              conda-forge/win-64::numpy-1.19.5-py36h4b40d73_2
  pip                conda-forge/noarch::pip-21.3.1-pyhd8ed1ab_0
  python             conda-forge/win-64::python-3.6.15-h39d44d4_0_cpython
  python_abi         conda-forge/win-64::python_abi-3.6-2_cp36m
  setuptools         conda-forge/win-64::setuptools-49.6.0-py36ha15d459_3
  tbb                conda-forge/win-64::tbb-2021.4.0-h2d74725_1
  ucrt               conda-forge/win-64::ucrt-10.0.20348.0-h57928b3_0
  vc                 conda-forge/win-64::vc-14.2-hb210afc_5
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.29.30037-h902a5da_5
  wheel              conda-forge/noarch::wheel-0.37.0-pyhd8ed1ab_1
  wincertstore       conda-forge/win-64::wincertstore-0.2-py36ha15d459_1006



Downloading and Extracting Packages
libblas-3.9.0        | 4.5 MB    | ########## | 100% 
liblapack-3.9.0      | 4.5 MB    | ########## | 100% 
libcblas-3.9.0       | 4.5 MB    | ########## | 100% 
intel-openmp-2021.4. | 3.2 MB    | ########## | 100% 
mkl-2021.4.0         | 181.7 MB  | ########## | 100% 
python_abi-3.6       | 4 KB      | ########## | 100% 
tbb-2021.4.0         | 149 KB    | ########## | 100% 
python-3.6.15        | 18.9 MB   | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use
#
#     $ conda activate r-reticulate
#
# To deactivate an active environment, use
#
#     $ conda deactivate

* Miniconda has been successfully installed at "C:/Users/Admin.DESKTOP-6E4TROE/AppData/Local/r-miniconda".
[1] "C:/Users/Admin.DESKTOP-6E4TROE/AppData/Local/r-miniconda"
> library(text)
This is text (version 0.9.16). 
Text is new and still rapidly improving. 
Newer versions may have improved functions and updated defaults to reflect current understandings of the state-of-the-art. 
Please send us feedback based on your experience.
> text::textrpp_install(envname = "textrpp_condaenv2")
Proceed? 

1: No
2: Yes

Selection: 2
A new conda environment "textrpp_condaenv2" will be created and 
python required packages: torch==1.7.1, transformers==4.12.5, numpy, nltk will be installed.  Creating textrpp_condaenv2 conda environment for text installation...
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Admin.DESKTOP-6E4TROE\AppData\Local\r-miniconda\envs\textrpp_condaenv2

  added / updated specs:
    - python=3.9.0


The following NEW packages will be INSTALLED:

  ca-certificates    conda-forge/win-64::ca-certificates-2021.10.8-h5b45459_0
  openssl            conda-forge/win-64::openssl-1.1.1l-h8ffe710_0
  pip                conda-forge/noarch::pip-21.3.1-pyhd8ed1ab_0
  python             conda-forge/win-64::python-3.9.0-h7840368_5_cpython
  python_abi         conda-forge/win-64::python_abi-3.9-2_cp39
  setuptools         conda-forge/win-64::setuptools-59.4.0-py39hcbf5309_0
  sqlite             conda-forge/win-64::sqlite-3.37.0-h8ffe710_0
  tzdata             conda-forge/noarch::tzdata-2021e-he74cb21_0
  ucrt               conda-forge/win-64::ucrt-10.0.20348.0-h57928b3_0
  vc                 conda-forge/win-64::vc-14.2-hb210afc_5
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.29.30037-h902a5da_5
  wheel              conda-forge/noarch::wheel-0.37.0-pyhd8ed1ab_1


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use
#
#     $ conda activate textrpp_condaenv2
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Installing text required python packages...
Collecting torch==1.7.1
  Downloading torch-1.7.1-cp39-cp39-win_amd64.whl (184.0 MB)
Collecting transformers==4.12.5
  Downloading transformers-4.12.5-py3-none-any.whl (3.1 MB)
Collecting numpy
  Downloading numpy-1.21.4-cp39-cp39-win_amd64.whl (14.0 MB)
Collecting nltk
  Downloading nltk-3.6.5-py3-none-any.whl (1.5 MB)
Collecting typing-extensions
  Downloading typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting tqdm>=4.27
  Downloading tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Collecting tokenizers<0.11,>=0.10.1
  Downloading tokenizers-0.10.3-cp39-cp39-win_amd64.whl (2.0 MB)
Collecting regex!=2019.12.17
  Downloading regex-2021.11.10-cp39-cp39-win_amd64.whl (273 kB)
Collecting requests
  Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting sacremoses
  Downloading sacremoses-0.0.46-py3-none-any.whl (895 kB)
Collecting filelock
  Downloading filelock-3.4.0-py3-none-any.whl (9.8 kB)
Collecting pyyaml>=5.1
  Downloading PyYAML-6.0-cp39-cp39-win_amd64.whl (151 kB)
Collecting packaging>=20.0
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
Collecting huggingface-hub<1.0,>=0.1.0
  Downloading huggingface_hub-0.2.1-py3-none-any.whl (61 kB)
Collecting click
  Downloading click-8.0.3-py3-none-any.whl (97 kB)
Collecting joblib
  Downloading joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.6-py3-none-any.whl (97 kB)
Collecting colorama
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.9-py3-none-any.whl (39 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: urllib3, pyparsing, idna, colorama, charset-normalizer, certifi, typing-extensions, tqdm, six, requests, regex, pyyaml, packaging, joblib, filelock, click, tokenizers, sacremoses, numpy, huggingface-hub, transformers, torch, nltk
  WARNING: The script normalizer.exe is installed in 'C:\Users\Admin.DESKTOP-6E4TROE\AppData\Local\r-miniconda\envs\textrpp_condaenv2\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tqdm.exe is installed in 'C:\Users\Admin.DESKTOP-6E4TROE\AppData\Local\r-miniconda\envs\textrpp_condaenv2\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script sacremoses.exe is installed in 'C:\Users\Admin.DESKTOP-6E4TROE\AppData\Local\r-miniconda\envs\textrpp_condaenv2\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script f2py.exe is installed in 'C:\Users\Admin.DESKTOP-6E4TROE\AppData\Local\r-miniconda\envs\textrpp_condaenv2\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script huggingface-cli.exe is installed in 'C:\Users\Admin.DESKTOP-6E4TROE\AppData\Local\r-miniconda\envs\textrpp_condaenv2\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script transformers-cli.exe is installed in 'C:\Users\Admin.DESKTOP-6E4TROE\AppData\Local\r-miniconda\envs\textrpp_condaenv2\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts convert-caffe2-to-onnx.exe and convert-onnx-to-caffe2.exe are installed in 'C:\Users\Admin.DESKTOP-6E4TROE\AppData\Local\r-miniconda\envs\textrpp_condaenv2\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script nltk.exe is installed in 'C:\Users\Admin.DESKTOP-6E4TROE\AppData\Local\r-miniconda\envs\textrpp_condaenv2\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed certifi-2021.10.8 charset-normalizer-2.0.9 click-8.0.3 colorama-0.4.4 filelock-3.4.0 huggingface-hub-0.2.1 idna-3.3 joblib-1.1.0 nltk-3.6.5 numpy-1.21.4 packaging-21.3 pyparsing-3.0.6 pyyaml-6.0 regex-2021.11.10 requests-2.26.0 sacremoses-0.0.46 six-1.16.0 tokenizers-0.10.3 torch-1.7.1 tqdm-4.62.3 transformers-4.12.5 typing-extensions-4.0.1 urllib3-1.26.7

Installation is completed.

 Condaenv: textrpp_condaenv2 

Great work - do not forget to initialize the environment 
with textrpp_initialize().

> text::textrpp_initialize(condaenv = "textrpp_condaenv2")
textrpp python option is already set, text will use:
	condaenv = "textrpp_condaenv"
Error in py_run_file_impl(file, local, convert) : 
  ModuleNotFoundError: No module named 'torch'

**Comment by OscarKjell** [comment]
Please note that the textrpp_initialize() is still using your previous textrpp_condaenv. So now please restart your R session; and then do: text::textrpp_initialize(condaenv = "textrpp_condaenv2").

**Comment by tressoldi** [comment]
Fixed at last !!!!
Thank you very much for your assistance and patience.
All the best
Patrizio
