### ISSUE TITLE
Antonyms?

### ISSUE THREAD

**Issue by sebsilas** [OscarKjell/text#41]
In `text`, is it possible to get an output, like a similarity score, but which respects that words can be negatively correlated (i.e., are antonyms)? e.g.,
```

good_embedding <- text::textEmbed("good")$texts$texts
bad_embedding <- text::textEmbed("bad")$texts$texts
satisfactory_embedding <- text::textEmbed("satisfactory")$texts$texts

text::textSimilarity(good_embedding, bad_embedding)
# Would want a negative number here

text::textSimilarity(good_embedding, satisfactory_embedding)
# Would want a positive number here
```

Or can you suggest a way of achieving this?

Thank you.

**Comment by OscarKjell** [comment]
No we do not have such a function. Typically antonyms share a lot of meaning.
