### ISSUE TITLE
Consider adding ranger to package dependencies

### ISSUE THREAD

**Issue by dietrichson** [OscarKjell/text#45]
To avoid this at runtime:

Error in purrr::map(.x = results_nested_resampling$inner_resamples, .f = summarize_tune_results_rf, :

Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `purrr::pmap()`:
ℹ In index: 1.
Caused by error in `check_installs()`:
! This engine requires some package installs: 'ranger'

**Comment by OscarKjell** [comment]
Thank you for your feedback! The `ranger`-package is currently under Suggests – and at the moment we can't move it to Imports because of CRAN's limit of having no more than 20 packages under Imports.
