### ISSUE TITLE
Classification with `textFineTuneTask()` failing

### ISSUE THREAD

**Issue by MattCowgill** [OscarKjell/text#51]
Hi, 

I am currently unable to use `textFineTuneTask()` for classification. It is working for regression. An example is below. Please let me know if I am using the function wrong (there is no example in the documentation, so it's hard to be sure). 

Thank you

**Initialise session:**
```
library(text)
library(tidyverse)

text::textrpp_install(rpp_version = c("torch==1.13.0",
                                      "transformers==4.19.2",
                                      "numpy",
                                      "nltk",
                                      "scikit-learn",
                                      "datasets",
                                      "evaluate"),
                      prompt = FALSE)

textrpp_initialize()

text <- Language_based_assessment_data_8 |> 
  filter(row_number() <= 20) |> 
  select(harmonytexts, gender) 

text_num <- text |> 
  mutate(gender = if_else(gender == "female", 0, 1))
```

**Classification does not work**
```
textFineTuneTask(text,
                 is_regression = FALSE)

Error:
! TypeError: object of type 'NoneType' has no len()
```

**Regression works**
```
textFineTuneTask(text_num,
                 is_regression = TRUE)
           
```

**Comment by MattCowgill** [comment]
If there is something wrong with the way I am attempting to use the function in the example above, I’d appreciate any help anyone can give.

**Comment by MattCowgill** [comment]
I've just tried the code above with the current GitHub version (1.0). I get the same result (ie. an error). If there is some other way this function is supposed to be used, I'd appreciate any pointers! The example in the function's help file is not complete (ie. is not a complete working example).

**Comment by MattCowgill** [comment]
Ok, sorry to have bothered you.

**Comment by MattCowgill** [comment]
I’ve now asked this question on SO in the hope that someone is able to provide a working example of using this function for classification. 

https://stackoverflow.com/questions/76223255/how-can-i-use-texttextfinetunetask-for-text-classification-problems

**Comment by MattCowgill** [comment]
The problem appears to be here: https://github.com/OscarKjell/text/blob/4348f3cf7780e99397f23d75baae11268e9f02f7/inst/python/task_finetune.py#L266-L272

`label_names` is getting passed a string, rather than a ClassLabel. See related issue here: https://github.com/huggingface/datasets/issues/5262

Thanks to @bennywee for uncovering this error.

**Comment by MattCowgill** [comment]
k cool

**Comment by OscarKjell** [comment]
Hi, sorry for a late reply.
If you reinstall the GitHub version of the text package – and then reinstall the text package:


```
devtools::install_github("oscarkjell/text")
library(text)
textrpp_install()
textrpp_initialize() 
```

 This will ensure that you install the right version of the Python package datasets 2.9.0. 
 
 Last, please also ensure to set the label_names parameter, for example: 
 
```
 textFineTuneTask(text_num,
                 is_regression = FALSE, 
                 label_names = c("male", "female")
                 )
```

**Comment by MattCowgill** [comment]
Thanks @OscarKjell. 

This still fails for me. I get: 

```
Error in `py_call_impl()`:
! AttributeError: 'Value' object has no attribute 'names'
```

I suspect this is related to the issue above https://github.com/OscarKjell/text/issues/51#issuecomment-1543195628
