### ISSUE TITLE
Minor issue with latest tidyr (1.3.0)

### ISSUE THREAD

**Issue by zilinskyjan** [OscarKjell/text#53]
Thank you for the fantastic package, Oscar.

One small thing I figured I would flag: specifying the `id_cols` argument by position was deprecated in tidyr 1.3.0.

So, for example `text::textZeroShot()` works, but the user will get the warning:

> Please explicitly name `id_cols`, like `id_cols = sequence`.

**Comment by OscarKjell** [comment]
Thanks for this – it has now been addressed.
