### ISSUE TITLE
Error in `dplyr::bind_cols()`:

### ISSUE THREAD

**Issue by tressoldi** [OscarKjell/text#56]
If I use roberta-base model instead of the bert-base-uncased, that works properly, I got:

word_embeddings <- textEmbed(Language_based_assessment_data_8, 
                            model = 'roberta-base',
                            aggregation_from_layers_to_tokens="concatenate",
                            aggregation_from_tokens_to_texts="mean",
                            keep_token_embeddings=FALSE
)

Error in `dplyr::bind_cols()`:
! Can't recycle `..1` (size 120) to match `..2` (size 78).
Run `rlang::last_trace()` to see where the error occurred.

**Comment by OscarKjell** [comment]
Hi, thanks for the feedback. This works if you use a newer version from github: 

`devtools::[install_github](https://remotes.r-lib.org/reference/install_github.html)("oscarkjell/text")`
