### ISSUE TITLE
Understanding the output

### ISSUE THREAD

**Issue by czopluoglu** [OscarKjell/text#6]
Hi,

Thank you for this package. This is really great. My issue is more about putting a little bit more explanation about output of these functions. 

For instance, when I run the following code, the function returns a list of Tibble objects.

```
 b <- textEmbed(x ="My name is Max. I am very happy.",
+ model = 'roberta-base',layers=12)
```

`b$x` is a 1 x 768 vector. 

`b$singlewords` is an 8 x 770 matrix.

I understand that the sentence has 8 tokens, so the second object returns embeddings for each word. However, I am not sure  what `b$x` represents. Does it represent the embeddings for the whole sentence? If I want to use the embeddings as predictive features, should I be using the numbers from `b$x`.

Also, I realize that `b$x` returns a 1 x 1536 vector when `layers = 11:12`. So, I assume the first 768 columns are embeddings from layer 11 (for the whole sentence???) and the second 768 columns are embeddings from layer 12 (for the whole sentence???). If I want to use these embeddings as predictive features, should I be aggregating these columns from layer 11 and layer 12, and it represents the embeddings for the whole sentence.

Sorry if the questions are dumb. A newbie trying to understand the output of these language models.

Thank you.

**Comment by OscarKjell** [comment]
Hi, 
`textEmbed()` represents the entire sentence (input) aggregated according the settings of `context_aggregation_layers ` ,
  `context_aggregation_tokens`. 
  Please note that `textEmbed()` include both `textEmbedLayersOutput()` and `textEmbedLayerAggregation()`, which might be worth playing around with to get a better understanding. 
  You can find more information at www.r-text.org and in our preprint at https://psyarxiv.com/293kt 
  Please let me know if something is unclear.
