### ISSUE TITLE
Error with textPredict function in the tutorial

### ISSUE THREAD

**Issue by lilchow** [OscarKjell/text#63]
I ran the following code exactly as printed in the tutorial (both valence_Warriner_L11 and word_embeddings were loaded from the zip downloaded from osf.):
`satisfaction_text_valence <- textPredict(
  valence_Warriner_L11,
  word_embeddings$texts$satisfactiontexts,
  dim_names = F)`

However, instead of showing the output printed in the tutorial, I got an error message:
`error in `recipes::bake()`: ! The following required columns are missing from `new_data`: "id_nr". ℹ These columns have one of the following roles, which are required at `bake()` time: "id variable". ℹ If these roles are not required at `bake()` time, use `update_role_requirements(role = "your_role", bake = FALSE)`. Backtrace:   1. text::textPredict(...)  10. workflows:::predict.workflow(...)  11. workflows:::forge_predictors(new_data, workflow)  13. hardhat:::forge.data.frame(new_data, blueprint = mold$blueprint)  15. hardhat:::run_forge.default_recipe_blueprint(...)  16. hardhat:::forge_recipe_default_process(...)  18. recipes:::bake.recipe(object = rec, new_data = new_data)`

Could you look into the problem when you have a moment? Thank you very much!

**Comment by OscarKjell** [comment]
1. Please first try to install the newest text-pacakge from GitHub: 
 
devtools::[install_github](https://remotes.r-lib.org/reference/install_github.html)("oscarkjell/text")

2. If it still does not work, you could try to train a new valence model and then try applying it.
