### ISSUE TITLE
issue with `text_ textTrainRegression`

### ISSUE THREAD

**Issue by scm1210** [OscarKjell/text#69]
Hi,

I've been playing around with the package for a project trying to model how embeddings of ppts responses can predict their emotion scores. However, we I go to model the data I keep running into the following error 

```> results <- textTrainRegression(
+   x = pos_word_embeddings$texts$text,
+   y = pos$day4_posemo,
+   multi_cores = FALSE # This is FALSE due to CRAN testing and Windows machines.
+ )
Error in `purrr::map()`:
ℹ In index: 1.
Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `purrr::pmap()`:
ℹ In index: 1.
Caused by error in `tidyr::drop_na()`:
! Can't rename variables in this context.
```
`pos$day4_posemo` is a numeric column. 

I've generated my embeddings as follows, where `positive_text` is just a dataframe with a text column.:

```
pos_word_embeddings <- textEmbed(positive_text,
                                 model = "bert-base-uncased",
                                 layers = -2,
                                 aggregation_from_layers_to_tokens = "concatenate",
                                 aggregation_from_tokens_to_texts = "mean",
                                 aggregation_from_tokens_to_word_types = "mean",
                                 keep_token_embeddings = F)
```

Apologies if im missing something clear and obvious.  I also replicated this error using the github version of the package

**Comment by OscarKjell** [comment]
Hi, 
Can you provide  example data that produce the same error? 
Thanks,
Oscar
