### ISSUE TITLE
Python error with other models

### ISSUE THREAD

**Issue by nicebread** [OscarKjell/text#7]
The textEmbed function works fine with "bert-base-german-dbmdz-uncased", but fails with other models, such as "distilbert-base-german-cased" or "dbmdz/distilbert-base-german-europeana-cased".

The models are successfully downloaded, but throw this error:

```
Fehler in py_call_impl(callable, dots$args, dots$keywords) : 
  IndexError: tuple index out of range

Detailed traceback:
  File "<string>", line 88, in hgTransformerGetEmbedding
  File "<string>", line 88, in <listcomp>
```

**Comment by OscarKjell** [comment]
thanks for letting us know, we're looking into it...

**Comment by OscarKjell** [comment]
sorry for getting back late – what did you run; did you make sure to not ask dilstillbert for too many layers? For example, this works for me: 

`textEmbed("hello", model = "distilbert-base-german-cased", layers = 4)`

**whereas, this does not work:** 

`textEmbed("hello", model = "distilbert-base-german-cased", layers = 7)`
