### ISSUE TITLE
Error in py_run_file_impl(file, local, convert) :    NameError: name '_C' is not defined

### ISSUE THREAD

**Issue by nelsonlrdsantos** [OscarKjell/text#73]
Hi, 

I've been using text package on another laptop and everything runs smoothly. However, on a different laptop, I've been trying to install the package (I have reinstall it, reinstall r as well), but when I tried to initialize (textrpp_initialize()), I'am receiving the following error: textrpp python option is already set, text will use: condaenv = "textrpp_condaenv"
Error in py_run_file_impl(file, local, convert) : 
  NameError: name '_C' is not defined
Run `reticulate::py_last_error()` for details.

I run the command for further details, and I get the following information:

 ── Python Exception Message ────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "C:/Users/nelso/AppData/Local/R/win-library/4.3/text/python/huggingface_Interface3.py", line 5, in <module>
    import torch
  File "C:\Users\nelso\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "C:\Users\nelso\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "C:\Users\nelso\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "C:\Users\nelso\AppData\Local\R-MINI~1\envs\TEXTRP~1\lib\site-packages\torch\__init__.py", line 457, in <module>
    for name in dir(_C):
NameError: name '_C' is not defined

── R Traceback ─────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─text::textrpp_initialize(...)
 2.   └─reticulate::source_python(...)
 3.     └─reticulate::py_run_file(file, local = FALSE, convert = convert)
 4.       └─reticulate:::py_run_file_impl(file, local, convert)

Any idea of what it can be? Thank you!

**Comment by moomoofarm1** [comment]
I think you should delete manually all the files and folders under site-packages folder. 
But before the deletion, you should have a backup somewhere else.
Sometimes a previous installation would hinder the text package to install.

**Comment by ryangraceintel** [comment]
I am having the same error here.  Where is the site-packages directory in Windows?  I searched my drive contents but don't see a directory with that name.

**Comment by nelsonlrdsantos** [comment]
Thank you for your answer. I tried to do what you told me. In fact, I have even uninstalled R and deleted all the packages. Re-installed everything, but it still doesn't work and the error is exactly the same. 
In fact, when I tried to initialize with the following command `textrpp_initialize(save_profile = TRUE)`, the error that I get is the following: `Error in py_run_file_impl(file, local, convert) : 
  TypeError: the first argument must be callable`

Nevertheless, if I try to `textrpp_initialize()`, the same error emerges again. 

Could it be any other thing? Thanks!

**Comment by lrodeck** [comment]
I am getting the same error today. Could it be due to other updates in packages? Spent sometime yesterday updating my packages. Maybe the last reticulate update broke it? When I used text yesterday it still works today I get the error above.

Working on windows 11

**Comment by moomoofarm1** [comment]
The key here I believe is still the path of the miniconda. You need to delete the whole folder and then try the [steps](https://r-text.org/articles/huggingface_in_r_extended_installation_guide.html) in this link. The link in my previous message works for my Mac and may not work for Win10.

**Comment by moomoofarm1** [comment]
> After following the steps in the link you made available (as far as possible, as I'm working on windows 10), the error that now I'm getting is the following: `Error in py_run_file_impl(file, local, convert) : ModuleNotFoundError: No module named 'torch'`. I don't get it, since I have installed the 'torch' in the following way: ` reticulate::conda_install(envname="textrpp_condaenv", packages=c("torch"), pip=TRUE)`.

The key here I believe is still the path of the miniconda. You need to delete the whole folder and then try the [steps](https://r-text.org/articles/huggingface_in_r_extended_installation_guide.html) in this link. The link in my previous message works for my Mac and may not work for Win10.

**Comment by moomoofarm1** [comment]
> I am getting the same error today. Could it be due to other updates in packages? Spent sometime yesterday updating my packages. Maybe the last reticulate update broke it? When I used text yesterday it still works today I get the error above.
> 
> Working on windows 11

It should not be. You can use the command reticulate::py_list_packages("textrpp_condaenv") to display a list of installed python packages. If you find torch there then it should not have such issue.
