### ISSUE TITLE
Replicating embeddings with transformers package

### ISSUE THREAD

**Issue by NewUser36** [OscarKjell/text#8]
Hello,

I tried using the package and as a verification of my code, I tried to replicate the embeddings I get with BERT, without success. I read the preprint paper, and took a look at the source code for TextEmbed, but I haven't been able to pinpoint where the difference could be coming from.

Here's my code using the transformers library (with the reticulate package).

```
# method from huggingface
library(reticulate)
transformer = reticulate::import('transformers') # transformers version: 3.3.1
torch = reticulate::import('torch') # torch version: 1.9.0

tokenizer <- transformer$BertTokenizer$from_pretrained('bert-base-uncased')
model <- transformer$BertModel$from_pretrained("bert-base-uncased")

encoded_sentence = tokenizer$encode(tokenizer$tokenize("Replace me by any text you'd like."), return_tensors='pt')
embeddings = model(encoded_sentence)

embeddings[[1]][0][0] # CLS token embedding from last hidden state
```
The result is 
```
tensor([ 1.3863e-01,  1.5827e-01, -2.9666e-01, -1.8494e-01, -4.6429e-01,
        -5.0329e-01, -6.2408e-04,  1.0469e+00, ...
```
Here's the code using `text` :

```
# with text package

texte = data.frame(text=c("Replace me by any text you'd like."))
texte_embedding <- textEmbed(texte, 
                          model="bert-base-uncased",
                          layers = 12,
                          #context_tokens_select="[CLS]",  # does not change resulting embeddings
                          #context_aggregation_layers="mean")

texte_embedding$text
```
which returns the following vector : 
`0.310 -0.107 0.204 -0.0771 -0.132 -0.399 0.293 0.902...`

I expected this to give the same vector I got in python. I am using the same virtual environment in both cases. It is a new virtual environment, and when I install text, it automatically installs transformers 3.3.1 in the environment. Is this expected behavior? If so, what is `text` doing differently?

Thanks for the help.

**Comment by OscarKjell** [comment]
Thank you for a, interesting, clearly stated question :) 
Please note that `textEmbed` is aggregating the embeddings from all tokens including CLS and words; and you seem to be looking at the CLS only in your python output. 
`textEmbed` is based on `textEmbedLayersOutput()` and `textEmbedLayerAggregation()`. So I suggest to only use the former function here to inspect the output from only the [CLS] 

```
texte = data.frame(text=c("Replace me by any text you'd like."))

texte_embedding <- textEmbedLayersOutput(texte, 
                      model="bert-base-uncased",
                      decontexts = FALSE,
                      layers = 12)

texte_embedding

# look at the first row which is the [CLS] embedding 
texte_embedding$context$text[[1]][1,]
```

I hope this help. (We should make this more clear on the site or preprint)

**Comment by NewUser36** [comment]
Great! Thanks for the help :)

Just to make sure, when you aggregate the embeddings with `textEmbedLayerAggregation()`, every token are used in the aggregation by default, including [CLS] and [SEP]?

**Comment by OscarKjell** [comment]
Yes, you can remove or only select them using 
tokens_select and tokens_deselect (see http://r-text.org/reference/textEmbedLayerAggregation.html )
