### ISSUE TITLE
Unaible to embed one word

### ISSUE THREAD

**Issue by NewUser36** [OscarKjell/text#9]
Hello,

When I try to embed a single word, I get an error (the same error I get when I try to embed an empty string, but in the case of the empty string, I expect to have an error). This error does not happen when I use python's transformers library.

Here's my code: 

```
library("text")

# empty string
texte = data.frame(text=c(""))
texte_embedding <- textEmbed(texte, 
                          model="camembert-base",
                          layers = 12)

# word tokenized as one token by camembert tokenizer
texte = data.frame(text=c("petit"))
texte_embedding <- textEmbed(texte, 
                          model="camembert-base",
                          layers = 12)
```

In both cases, I get the error
```
Error in x[[1]] : subscript out of bounds
In addition: Warning message:
Unknown or uninitialised column: `words`. 
```

There is no error when I use a longer text, for instance "petit test". The version of the package I'm using is 0.9.10.

Thanks!

**Comment by OscarKjell** [comment]
Hi,
Thanks for the feedback. This has now been fixed if you install the latest package version (.9.12) from GitHub. 
Oscar
