### ISSUE TITLE
Problem with the textTrainRegression using multinomial

### ISSUE THREAD

**Issue by Batotai** [OscarKjell/text#92]
Hi everybody ! I'm trying to estimate a multinomial model where my x are the embeddings of some sentences, and y is a factor variable with 4 different categories. There are 1079 sentences and the embedding has been done with bert_uncased (so the x variable is really a list of 768 "Dim" variables).

The estimation process looks to run smoothly BUT when it is done, there's an error message on a Fisher test impossible to compute and no model output I can use : 

Error in stats::fisher.test(predy_y$truth, predy_y$estimate) : 
  FEXACT error 501.
The hash table key cannot be computed because the largest key
is larger than the largest representable int.
The algorithm cannot proceed.
Reduce the workspace, consider using 'simulate.p.value=TRUE' or another algorithm.

I cannot locate the file where this test is done so I cant modify the option as R suggests (but may be it's not the cause of the problem ?).

I tried reducing the number of categories to 3 and to 2, or change them all to positive integer (originally my variable takes the values of "-2", "-1", "0" and "1") but always got the same error message...

Any help would be more than welcome !!

[printscreen.docx](https://github.com/OscarKjell/text/files/13379779/printscreen.docx)

**Comment by OscarKjell** [comment]
Thank you for the feedback. Have you tried to set `simulate.p.value=TRUE `in **textTrainRegression()**?
